### ISSUE TITLE
Proposed Enhancement: for AlgebraicDataTypes/ChapterExercises/AsPatterns.hs

### ISSUE THREAD

**Issue by m1nhtu99-hoan9** [BoeingX/haskell-programming-from-first-principles#3]
At [`src/AlgebraicDataTypes/ChapterExercises/AsPatterns.hs`](https://github.com/BoeingX/haskell-programming-from-first-principles/blob/master/)

## Expected: 
``` Haskell
isSubsequenceOf "blah" "wootbla" == False
isSubsequenceOf "blah" "halbwoot" == False
```
as stated in page 695 of the eBook "Haskell from the First Principle"

## Actual: 
```Haskell
isSubsequenceOf "blah" "wootbla" == True
isSubsequenceOf "blah" "halbwoot" == True
```

## Proposed enhancement: 

```Haskell
  indexOf :: (Eq a) => a -> [a] -> Int
  indexOf x ys = case elemIndex x ys of 
    Just a -> a 
    Nothing -> -1

  splitBy :: (Eq a) => a -> [a] -> ([a], [a])
  splitBy x = span (/= x)

  joinWithout :: (Eq a) => a -> [a] -> [a]
  joinWithout x ys = let (a, b) = splitBy x ys in (a ++ tail b)  

  isSubseqOf :: (Eq a) => [a] -> [a] -> Bool
  isSubseqOf [] _ = True 
  isSubseqOf _ [] = False
  -- @TODO: strip each element of the referenced list after each recursion
  isSubseqOf (x : xs) ys 
    | null ys'' = False
    | otherwise = 
        case xs of 
          (z : _) -> 
            let idX = indexOf x ys
                idZ = indexOf z ys in
            case (compare idX idZ) of 
              LT -> isSubseqOf xs (joinWithout x ys)
              _  -> False
          _       -> isSubseqOf xs (joinWithout x ys)
    where (ys', ys'') = splitBy x ys
```

**Comment by BoeingX** [comment]
@mnhthng-thms Thank you for your feedback, I misunderstood the exact meaning of *subsequence*. The bug was fixed in [this commit](https://github.com/BoeingX/haskell-programming-from-first-principles/commit/a7f5e1d850ff42008934e6f450a944f2c6a50d68). By the way, thanks for your proposed solution. Though it works, it is a little bit too involved and does not use the at pattern...

PS: There is actually [an implementation](https://hackage.haskell.org/package/base-4.14.0.0/docs/src/Data.List.html#isSubsequenceOf) in the standard `Data.List` library.
